"""
AI Healer for P2T Post-Refresh Automation
==========================================
Uses local Gemma 4 via Ollama to analyze and fix UI automation failures.

WHAT IT DOES:
    1. Takes a screenshot of the current Oracle Fusion page
    2. Reads interactive DOM elements from the page
    3. Loads task knowledge (master doc steps + code steps) from knowledge/ folder
    4. Sends screenshot + DOM + error context + task knowledge to Gemma 4
    5. Gemma 4 analyzes what went wrong and suggests a Playwright selector fix
    6. Attempts to execute the fix (click, fill, wait)
    7. If fix works, automation continues; if not, retry system takes over
    8. Saves intervention results to healing_history.json for future learning

SETUP:
    1. Install Ollama: https://ollama.com/download
    2. Pull model: ollama pull gemma4:e4b
    3. Set AI_HEALER_ENABLED=true in .env

KNOWLEDGE SYSTEM:
    The AI healer loads two types of knowledge for each task:
    1. Master doc chunks (task_N_*.json) - general steps from the P2T master document
       Generated by: python chunk_master_doc.py knowledge/P2T_Master_Document-_(client).docx
    2. Code steps (code_N_*.json) - exact Playwright actions extracted from Ui_Automation.py
       Generated by: python extract_code_steps.py Ui_Automation.py
    Both are in the knowledge/ folder and loaded on demand when a task fails.

CONFIGURATION (.env):
    AI_HEALER_ENABLED=true/false    (default: false)
    AI_HEALER_MODEL=gemma4:e4b      (default: gemma4:e4b)
    AI_HEALER_URL=http://localhost:11434  (default: localhost)
    AI_HEALER_MAX_RETRIES=1         (default: 1)

PRIVACY:
    Everything runs locally via Ollama. No data leaves your machine.
"""
from __future__ import annotations

import base64
import json
import os
import re
from pathlib import Path
from playwright.sync_api import Page

try:
    import ollama
    OLLAMA_AVAILABLE = True
except ImportError:
    OLLAMA_AVAILABLE = False

KNOWLEDGE_DIR = Path(__file__).resolve().parent / "knowledge"
HEALING_HISTORY_PATH = KNOWLEDGE_DIR / "healing_history.json"


class AIHealer:
    def __init__(self, model=None, ollama_url=None, max_retries=None):
        self.model = model or os.getenv("AI_HEALER_MODEL", "gemma4:e4b")
        self.ollama_url = ollama_url or os.getenv("AI_HEALER_URL", "http://localhost:11434")
        self.max_retries = max_retries or int(os.getenv("AI_HEALER_MAX_RETRIES", "1"))
        self.interventions = []
        self.enabled = os.getenv("AI_HEALER_ENABLED", "false").lower() == "true"
        if not OLLAMA_AVAILABLE and self.enabled:
            print("[AI Healer] WARNING: ollama not installed. Run: pip install ollama")
            self.enabled = False

    # == KNOWLEDGE LOADING ==

    def _load_task_knowledge(self, task_name):
        """Load master doc steps + code steps for a task from knowledge/ folder."""
        if not KNOWLEDGE_DIR.exists():
            return ""
        num_match = re.search(r'(?:task\s*)?(\d+)', task_name, re.I)
        if not num_match:
            return ""
        task_num = num_match.group(1)
        parts = []

        # Master doc chunks
        for p in sorted(KNOWLEDGE_DIR.glob(f"task_{task_num}_*.json")):
            try:
                c = json.loads(p.read_text(encoding="utf-8"))
                parts.append(
                    f"=== MASTER DOCUMENT: {c.get('task_name','')} ===\n"
                    f"Steps:\n{c.get('steps','')}\n"
                    f"Expected elements: {', '.join(c.get('expected_elements',[]))}"
                )
            except Exception:
                pass

        # Code steps
        for p in sorted(KNOWLEDGE_DIR.glob(f"code_{task_num}_*.json")):
            try:
                c = json.loads(p.read_text(encoding="utf-8"))
                parts.append(
                    f"=== CODE STEPS: {c.get('function_name','')} ===\n"
                    f"{c.get('code_steps_readable','')}"
                )
            except Exception:
                pass

        return "\n\n".join(parts)

    def _load_healing_history(self, task_name):
        """Load past healing interventions for this task."""
        if not HEALING_HISTORY_PATH.exists():
            return ""
        try:
            history = json.loads(HEALING_HISTORY_PATH.read_text(encoding="utf-8"))
        except Exception:
            return ""
        num_match = re.search(r'(?:task\s*)?(\d+)', task_name, re.I)
        if not num_match:
            return ""
        task_num = num_match.group(1)
        task_history = [h for h in history if str(h.get("task_num","")) == task_num]
        if not task_history:
            return ""
        lines = ["=== PAST HEALING HISTORY ==="]
        for h in task_history[-5:]:
            worked = "WORKED" if h.get("fix_applied") else "FAILED"
            lines.append(f"- Error: {h.get('error','')[:100]}\n  Selector: {h.get('fix_selector','')}\n  Result: {worked}")
        return "\n".join(lines)

    def _save_to_healing_history(self, intervention):
        """Save intervention result for future learning."""
        try:
            history = []
            if HEALING_HISTORY_PATH.exists():
                history = json.loads(HEALING_HISTORY_PATH.read_text(encoding="utf-8"))
            KNOWLEDGE_DIR.mkdir(exist_ok=True, parents=True)
            task_name = intervention.get("task_name", "")
            num_match = re.search(r'(?:task\s*)?(\d+)', task_name, re.I)
            history.append({
                "task_num": num_match.group(1) if num_match else "0",
                "task_name": task_name,
                "error": intervention.get("error", "")[:200],
                "fix_applied": intervention.get("fix_applied", False),
                "fix_selector": intervention.get("fix_selector", ""),
                "fix_action": intervention.get("fix_action", ""),
            })
            history = history[-100:]
            HEALING_HISTORY_PATH.write_text(json.dumps(history, indent=2), encoding="utf-8")
        except Exception as e:
            print(f"[AI Healer] Could not save healing history: {e}")

    # == PAGE ANALYSIS ==

    def _screenshot_to_base64(self, page):
        return base64.b64encode(page.screenshot(full_page=False)).decode("utf-8")

    def _get_page_summary(self, page):
        try:
            elements = page.evaluate("""() => {
                const items = [];
                const sels = ['button','a','input','select','textarea',
                    '[role="button"]','[role="link"]','[role="textbox"]',
                    '[role="menuitem"]','[role="tab"]','[role="checkbox"]',
                    '[role="combobox"]','[role="option"]','[role="dialog"]',
                    '[role="row"]','[role="cell"]','[role="heading"]',
                    '[onclick]','[tabindex]'];
                sels.forEach(s => {
                    document.querySelectorAll(s).forEach(el => {
                        if (el.offsetParent !== null) {
                            items.push({
                                tag: el.tagName, role: el.getAttribute('role')||'',
                                name: el.getAttribute('name')||'',
                                text: (el.textContent||'').trim().substring(0,80),
                                id: el.id||'', type: el.type||'',
                                ariaLabel: el.getAttribute('aria-label')||'',
                                title: el.getAttribute('title')||'',
                                ariaDisabled: el.getAttribute('aria-disabled')||''
                            });
                        }
                    });
                });
                return items.slice(0,60);
            }""")
            return str(elements)
        except Exception:
            return "Could not read page elements"

    def analyze_page(self, page, task_description=""):
        if not self.enabled:
            return "[AI Healer] Disabled"
        screenshot_b64 = self._screenshot_to_base64(page)
        page_elements = self._get_page_summary(page)
        prompt = f"""You are an Oracle Fusion Cloud automation expert for (client) P2T post-refresh tasks.
Describe what you see on this page. What page of Oracle Fusion Cloud is this?
Interactive elements: {page_elements}
{f"The automation is trying to: {task_description}" if task_description else ""}"""
        response = ollama.chat(model=self.model, messages=[{"role":"user","content":prompt,"images":[screenshot_b64]}])
        return response["message"]["content"]

    # == FIX SUGGESTION (Enhanced with knowledge) ==

    def suggest_fix(self, page, task_name, failed_action, error_message):
        screenshot_b64 = self._screenshot_to_base64(page)
        page_elements = self._get_page_summary(page)
        task_knowledge = self._load_task_knowledge(task_name)
        healing_history = self._load_healing_history(task_name)

        knowledge_section = ""
        if task_knowledge:
            knowledge_section += f"\nTASK KNOWLEDGE (master doc + code):\n{task_knowledge}\n"
        if healing_history:
            knowledge_section += f"\n{healing_history}\n"

        prompt = f"""You are an Oracle Fusion Cloud automation expert. A Python Playwright automation got stuck during a P2T post-refresh task.

TASK NAME: {task_name}

WHAT THE CODE TRIED TO DO:
{failed_action}

ERROR MESSAGE:
{error_message}
{knowledge_section}
INTERACTIVE ELEMENTS ON PAGE:
{page_elements}

Based on the screenshot, error, task knowledge, and elements above:
1. What is on the screen?
2. Why did the code fail? Compare what happened vs what the master document says should happen.
3. Which element should be interacted with instead?
4. Give the exact Playwright Python selector.

SELECTOR RULES:
- Prefer page.get_by_role() over page.get_by_text()
- Include role type (button, link, textbox) for specificity
- Use page.locator("#id") as fallback if element has an id
- Oracle uses AFModalGlassPane overlays - suggest waiting if visible
- For Additional Details sections, click heading first to activate before selecting rows
- Use .last or .nth() when multiple matching elements exist

Respond in this exact format:
EXPLANATION: (what you see and why it failed)
SELECTOR: (e.g., page.get_by_role("button", name="Sign In"))
ACTION: (click, fill, or wait)"""

        response = ollama.chat(model=self.model, messages=[{"role":"user","content":prompt,"images":[screenshot_b64]}])
        answer = response["message"]["content"]
        self.interventions.append({"task_name":task_name,"failed_action":failed_action,"error":error_message,"ai_response":answer})
        return {"raw_response":answer,"intervention_count":len(self.interventions)}

    # == FIX EXECUTION ==

    def attempt_fix(self, page, task_name, failed_action, error_message):
        if not self.enabled:
            return False
        print(f"\n[AI Healer] Task stuck: {task_name}")
        print(f"[AI Healer] Failed action: {failed_action}")
        print(f"[AI Healer] Error: {error_message[:200]}")

        knowledge = self._load_task_knowledge(task_name)
        if knowledge:
            print(f"[AI Healer] Loaded knowledge ({len(knowledge)} chars)")
        else:
            print(f"[AI Healer] No knowledge found for task")

        print(f"[AI Healer] Analyzing page with {self.model}...")
        try:
            suggestion = self.suggest_fix(page, task_name, failed_action, error_message)
        except Exception as e:
            print(f"[AI Healer] Failed to get suggestion: {e}")
            return False

        response_text = suggestion["raw_response"]
        print(f"[AI Healer] AI says:\n{response_text}")

        selector = None
        action = None
        for line in response_text.split("\n"):
            line = line.strip()
            if line.upper().startswith("SELECTOR:"):
                selector = line.split(":",1)[1].strip()
            elif line.upper().startswith("ACTION:"):
                action = line.split(":",1)[1].strip().lower()

        if not selector or not action:
            print("[AI Healer] Could not parse selector/action from response.")
            self.interventions[-1]["fix_applied"] = False
            self._save_to_healing_history(self.interventions[-1])
            return False

        print(f"[AI Healer] Attempting: {selector} -> {action}")
        try:
            element = eval(selector, {"page": page})
            if "click" in action:
                element.click(timeout=10000)
                print("[AI Healer] Click successful!")
            elif "fill" in action:
                element.click(timeout=10000)
                print("[AI Healer] Element focused!")
            elif "wait" in action:
                element.wait_for(state="visible", timeout=15000)
                print("[AI Healer] Element visible!")

            self.interventions[-1].update({"fix_applied":True,"fix_selector":selector,"fix_action":action})
            self._save_to_healing_history(self.interventions[-1])
            print("[AI Healer] FIX SUCCESSFUL!")
            return True
        except Exception as fix_error:
            print(f"[AI Healer] Fix failed: {fix_error}")
            self.interventions[-1].update({"fix_applied":False,"fix_error":str(fix_error),"fix_selector":selector,"fix_action":action})
            self._save_to_healing_history(self.interventions[-1])
            return False

    # == REPORTING ==

    def get_report(self):
        return self.interventions

    def print_report(self):
        if not self.interventions:
            print("[AI Healer] No interventions this run.")
            return
        print(f"\n{'='*60}")
        print(f" AI HEALER REPORT - {len(self.interventions)} intervention(s)")
        print(f"{'='*60}")
        for i, inv in enumerate(self.interventions, 1):
            print(f"\n  #{i}: {inv.get('task_name','N/A')}")
            print(f"    Failed: {inv['failed_action'][:100]}")
            print(f"    Fix applied: {inv.get('fix_applied','N/A')}")
            if inv.get('fix_selector'): print(f"    Selector: {inv['fix_selector']}")
            if inv.get('fix_error'): print(f"    Error: {inv['fix_error']}")
        print(f"{'='*60}\n")


_healer_instance = None
def get_healer():
    global _healer_instance
    if _healer_instance is None:
        _healer_instance = AIHealer()
    return _healer_instance


if __name__ == "__main__":
    if not OLLAMA_AVAILABLE:
        print("Ollama not installed. Run: pip install ollama")
        print("Then: ollama pull gemma4:e4b")
    else:
        print("Testing AI Healer...")
        healer = AIHealer()
        healer.enabled = True
        print("\nTesting knowledge loading...")
        for t in [1,3,16,22]:
            k = healer._load_task_knowledge(f"Task {t}")
            print(f"  Task {t}: {len(k)} chars" if k else f"  Task {t}: No knowledge")
        try:
            r = ollama.chat(model=healer.model, messages=[{"role":"user","content":"Say 'P2T AI Healer is online'"}])
            print(f"\nGemma 4: {r['message']['content']}")
            print("AI Healer ready!")
        except Exception as e:
            print(f"\nConnection failed: {e}\nMake sure Ollama is running: ollama serve")